// <auto-generated />
namespace Web_Banhngot_DoAnck.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class themdangkyvadangnhap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themdangkyvadangnhap));
        
        string IMigrationMetadata.Id
        {
            get { return "202511011208479_them dangky va dang nhap "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
